# Generated by Django 6.0 on 2026-01-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FireApp', '0003_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.URLField(default='example-slug'),
            preserve_default=False,
        ),
    ]
