# Generated by Django 6.0 on 2026-01-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FireApp', '0005_aboutus_category_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUS',
        ),
    ]
