# Generated by Django 6.0 on 2026-01-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FireApp', '0006_delete_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
